openapi: 3.0.1
info:
  title: Natours
  description: Сервис для покупки туров
  contact:
    email: vladislav.pestsov@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:4000/api/v1
paths:
  /reviews/{id}:
    patch:
      summary: Восстановления пароля по токену восстановления пароля
      tags:
        - authentification
      parameters:
          - in: path
            name: id
            schema:
              type: string
            required: true
            description: Токен восстановления пароля
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/editReviewForm'
      responses:
        200:
          description: Письмо с токеном восстановления пароля успешно отправлен на почту
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editReview_responses__200'
                
        401:
          description: Ошибка возникает если пользователь не залогинился, но пытается совершить действие
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editReview_responses_401'
          
        403:
          description: Ошибка возникает, когда действие пытается выполнить пользователь с ролью у которой отстутствуют права на совершения подобных действий.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editReview_responses_403'
        
        404:
          description: Нет комментария с данным ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editReview_responses__404'
        
        500: 
          description: Ошибка возникает если введён не правильный формат ID тура
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/editReview_responses_500'
                
components:
  schemas:
    editReviewForm:
      type: object
      properties:
        rating:
          type: number
          example: 4
        review:
          type: string
          example: Слишком большая группа, с меньшим количеством участников было бы проще
    
    editReview_responses__200:
      type: object
      properties:
        status:
          type: string
          example: success
        data: 
          type: object
          properties:
            data:
              type: object
              properties:
                _id:
                  type: string
                  example: 61d2e978e107e4436db7e55c
                review:
                  type: string
                  example: Слишком большая группа, с меньшим количеством участников было бы прощ
                rating:
                  type: string
                  example: 4
                tour:
                  type: string
                  example: 5c88fa8cf4afda39709c296c
                user:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 61cb790e567dc378ee45db53
                    name:
                      type: string
                      example: Виктор Левко
                    photo:
                      type: string
                      example: user-9.jpg
                createdAt:
                  type: string
                  format: date
                  example: "2022-01-03T12:18:00.227Z"
                id:
                  type: string
                  example: 61d2e978e107e4436db7e55c
                  
    editReview_responses_401:
      type: object
      properties:
        status:
          type: string
          example: fail
        error:
          type: object
          properties:
            statusCode:
              type: integer
              example: 401
            status: 
              type: string
              example: fail
            isOperational: 
              type: boolean
              example: true
        message:
          type: string
          example: Вы не залогинились! Пожалуйста ввойдите в вашу учётную запись
    
    editReview_responses_403:
      type: object
      properties:
        status:
          type: string
          example: fail
        error:
          type: object
          properties:
            statusCode:
              type: integer
              example: 403
            status: 
              type: string
              example: fail
            isOperational: 
              type: boolean
              example: true
        message:
          type: string
          example: Вы не владеете достаточными правами для совершения подобных действий
    
              
    editReview_responses__404:
      type: object
      properties:
        status:
          type: string
          example: fail
        error:
          type: object
          properties:
            statusCode:
              type: integer
              example: 404
            status: 
              type: string
              example: fail
            isOperational: 
              type: boolean
              example: true
        message:
          type: string
          example: Нет документa з данным ID
          
    editReview_responses_500:
      type: object
      properties:
        status: 
          type: string
          example: error
        error:
          type: object
          properties:
            stringValue: 
              type: string
              example: 5c88fa8cf4afda39709c294522
            valueType:
              type: string
              example: string
            kind: 
              type: string
              example: objectId
            value: 
              type: string
              example: 5c88fa8cf4afda39709c294522
            path: 
              type: string
              example: tour
            reason: 
              type: string
              example: {}
            name: 
              type: string
              example: CastError
            message: 
              type: string
              example: Cast to ObjectId failed for value "5c88fa8cf4afda39709c294522" (type string) at path "tour" for model "Review"
        message:
          type: string
          example: Cast to ObjectId failed for value "5c88fa8cf4afda39709c294522" (type string) at path "tour" for model "Review"
    