openapi: 3.0.1
info:
  title: Natours
  description: Сервис для покупки туров
  contact:
    email: vladislav.pestsov@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:4000/api/v1
paths:
  /users/resetPassword/{token}:
    patch:
      summary: Восстановления пароля по токену восстановления пароля
      tags:
        - authentification
      parameters:
          - in: path
            name: token
            schema:
              type: string
            required: true
            description: Токен восстановления пароля
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resetPasswordForm'
      responses:
        200:
          description: Письмо с токеном восстановления пароля успешно отправлен на почту
          content:
            application/json:
              schema:
                properties:
                  status:
                    type: string
                    example: 'success'
                  message:
                    type: string
                    example: Токен отправлен на почту
        400:
          description: Пользователя с данным Email не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/resetPassword_responses__400'
          
        
components:
  schemas:
    resetPasswordForm:
      type: object
      properties:
        password:
          type: string
          example: password123
        passwordConfirm:
          type: string
          example: password123
    
    resetPassword_responses__400:
      type: object
      properties:
        status:
          type: string
          example: fail
        error:
          type: object
          properties:
            statusCode:
              type: integer
              example: 400
            status: 
              type: string
              example: fail
            isOperational: 
              type: boolean
              example: true
        message:
          type: string
          example: Неверный токен или его срок годности истёк