openapi: 3.0.1
info:
  title: Natours
  description: Сервис для покупки туров
  contact:
    email: vladislav.pestsov@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:4000/api/v1
paths:
  /users/updateMyPasssword:
    patch:
      summary: Изменение действующего пароля пользователя на другой
      tags:
        - authentification
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateMyPasswordForm'
      responses:
        200:
          description: Письмо с токеном восстановления пароля успешно отправлен на почту
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/updateMyPassword_responses__200'
        401:
          description: Пользователя с данным Email не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/updateMyPassword_responses__401'
          
        
components:
  schemas:
    updateMyPasswordForm:
      type: object
      properties:
        passwordCurrent:
          type: string
          example: 12345678
        password:
          type: string
          example: password123
        passwordConfirm:
          type: string
          example: password123
    
    
    updateMyPassword_responses__200:
      type: object
      properties:
        status:
          type: string
          example: success
        token: 
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxY2I3N2Q3NTY3ZGMzNzhlZTQ1ZGI0OSIsImlhdCI6MTY0MzAxOTExMCwiZXhwIjoxNjUwNzk1MTEwfQ.MweQr8JkzmLJW7TUHGcE6-xmFSJFotbSgexUhRb8yQ0
        data: 
          type: object
          properties:
            user:
              $ref: '#/components/schemas/updateMyPassword_userForm_responses__200'
    
    updateMyPassword_userForm_responses__200:
      type: object
      properties:
        _id:
          type: string
          example: 61cb77d7567dc378ee45db49
        name:
          type: string
          example: Vladislav Pestsov
        email:
          type: string
          example: vladislav.pestsov@gmail.com
        role: 
          type: string
          example: user
        photo:
          type: string
          example: user-61cb77d7567dc378ee45db49-1641489907686.jpeg
        passwordChangedAt:
          type: string
          example: 2022-01-24T10:11:49.508Z
        passwordResetExpires:
          type: string
          example: 2022-01-24T10:04:24.573Z
        passwordResetToken:
          type: string
          example: 8759a136a875295aeafe65fc56a404d68d327761d1d70e38e7982bfc90ce0ca0
    
    
    updateMyPassword_responses__401:
      type: object
      properties:
        status:
          type: string
          example: fail
        error:
          type: object
          properties:
            statusCode:
              type: integer
              example: 401
            status: 
              type: string
              example: fail
            isOperational: 
              type: boolean
              example: true
        message:
          type: string
          example: Ваш текущий пароль не верный