openapi: 3.0.1
info:
  title: Natours
  description: Сервис для покупки туров
  contact:
    email: vladislav.pestsov@gmail.com
  version: 1.0.0
servers:
- url: http://localhost:4000/api/v1
paths:
  /users:
    get:
      parameters:
        - in: query
          name: duration
          example: duration[gte]=5
          schema:
            type: integer
          description: Больше или равно указаного количества дней которые занимает тур. Доступны следующие фильтры - 
            1. [gte] - больше или равно указаного количества. 
            2. [gt]- больше указаного количества. 
            3. [lte] - меньше или равно указаного количества.
            4. [lt]- меньше указаного количества людей.
        - in: query
          name: sort
          example: sort=maxGroupSize  
          schema:
            type: string
          description: Сортирует массив туров в зависимости от параметра сортировки. По умолчанию сортировка от меньшей стоимости к большей, чтобы инверсировать сортировку необходимо ввести вместо "sort=maxGroupSize" - "sort=maxGroupSize-1". Доступны следующие параметры сортировки - 
            1. price - сортировка по цене. 
            2. duration - сортировка по количеству дней продолжительности тура. 
            3. maxGroupSize - сортировка по количеству людей в одной групе.
            4. difficulty - сложность тура.
            5. ratingsQuantity - рейтинг тура
        - in: query
          name: limit
          example: limit=8
          schema:
            type: number
          description: Пагинация необходимого количество туров
      security:
        - bearerAuth: []
      summary: Получение массива всех туров
      tags:
        - tours
      responses:
        200:
          description: Получение массива всех туров
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllTours_responses_200'
        401:
          description: Ошибка возникает если пользователь не залогинился, но пытается совершить действие
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getAllTours_responses_401'
                        
components:
  securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    
    getAllTours_responses_200:
      type: array
      items:
        type: object
        properties:
          status:
            type: string
            example: success
          results:
            type: number
            example: 1
          data:
            type: object
            properties:
              data: 
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: 61cb77aa567dc378ee45db47
                    name:
                      type: string
                      example: Vladislav Pestsov
                    email:
                      type: string
                      example: vladislav.pestsov@gmail.com
                    role:
                      type: string
                      example: user
                    photo:
                      type: string
                      example: user-5.jpg

    getAllTours_responses_401:
      type: object
      properties:
        status:
          type: string
          example: fail
        error:
          type: object
          properties:
            statusCode:
              type: integer
              example: 401
            status: 
              type: string
              example: fail
            isOperational: 
              type: boolean
              example: true
        message:
          type: string
          example: Вы не залогинились! Пожалуйста ввойдите в вашу учётную запись
    
    